const weatherActionTypes = {
  FETCH_CURRENT_WEATHER_PENDING: 'FETCH_CURRENT_WEATHER_PENDING',
  FETCH_CURRENT_WEATHER_SUCCESS: 'FETCH_CURRENT_WEATHER_SUCCESS',
  FETCH_CURRENT_WEATHER_FAILURE: 'FETCH_CURRENT_WEATHER_FAILURE'
}

export default weatherActionTypes;